### ISSUE TITLE
Update icon missing

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#52]
The icon for downloading the Discord update is missing
![image](https://user-images.githubusercontent.com/36117192/43751961-a3e47442-99c4-11e8-88a2-12b6af246d33.png)

**Comment by silent** [comment]
This has been fixed on its own I guess.

**Comment by tryoutuser** [comment]
Not the same case for me, the update icon is still missing, though I also have SegoeMDL2 Assets installed.
